exact_source = [
  'exact.cpp'
]

exact_exe = executable(
  'exact',
  exact_source,
  dependencies : [axc_math_operators_dep],
  include_directories: include_dir
)

lut_source = [
  'lut.cpp'
]

lut_exe = executable(
  'lut',
  lut_source,
  dependencies : [axc_math_operators_dep],
  include_directories: include_dir
)

taylor_source = [
  'taylor.cpp'
]

taylor_exe = executable(
  'taylor',
  taylor_source,
  dependencies : [axc_math_operators_dep],
  include_directories: include_dir
)
