############################################################
## Copyright 2021-2022
## Author: Luis G. Leon-Vega <lleon95@estudiantec.cr>
############################################################

include helpers/coreops.mk
include helpers/help.mk
include helpers/rules.mk
include helpers/welcome.mk

# --- Top rules ---
.PHONY: synthesis clean help

SUBDIRS = tests
ALL_SUBDIRS = $(SUBDIRS)

synthesis:
	$(info $(WELCOME_MESSAGE))
	$(info Synthesising modules: $(TEST))

help:
	$(info $(WELCOME_MESSAGE))
	$(info $(HELP_MESSAGE))

clean:
	$(info $(WELCOME_MESSAGE))
	$(info Cleaning projects)

clean-all:
	$(info $(WELCOME_MESSAGE))
	$(info Cleaning projects)
