# Include subproject dirs:
incdirs += [
  'ext/hls-types/include',
  'ext/axc-math',
  'ext/hls-math',
  'ext/matrix/includes',
  'ext'
]

# FAL specific
incdirs += [
  'ext/fal-accels/include',
  'ext/fal-accels/examples',
  'ext/fal-accels/convolution/include',
  'ext/hls-stream',
]

fal_sources = meson.source_root() + '/ext/fal-accels/examples'
