option('developer-mode', type : 'boolean', value : true, yield : true, description: 'Enable developer mode')
option('debug-mode', type : 'boolean', value : false, yield : true, description: 'Enable debugging mode')
option('arithmetic-mode', type : 'combo', choices : ['EXACT', 'LSBDROP', 'LSBOR', 'LSBFIXED'], value : 'EXACT', description: 'Approximation mode of the arithmetic kernels')
option('developer-mode', type : 'boolean', value : true, yield : true, description: 'Enable developer mode')
option('axc-external', type : 'integer', min : 14, max : 24, value : 20, description: 'Number of bits for external layers')
option('axc-internal', type : 'integer', min : 10, max : 20, value : 16, description: 'Number of bits for internal layers')
option('axc-integer', type : 'integer', min : 1, max : 8, value : 6, description: 'Number of integer bits for Fixed-Point')
option('axc-width', type : 'integer', min : 4, max : 16, value : 14, description: 'Number of bits for Fixed-Point')
option('axc-drop', type : 'integer', min : 1, max : 8, value : 2, description: 'Number of bits to drop in AxC Math')
option('matrix-multiplier', type : 'combo', choices : ['MatrixMultiplyAdd', 'MatrixMultiplyAddStrassen', 'MatrixMultiplyAddWinograd'], value : 'MatrixMultiplyAdd', description: 'Matrix Multiply Core')
option('accelerators', type : 'combo', choices : ['None', 'Emulated'], value : 'None', description: 'Enables the accelerator logic where it is possible')
